### ISSUE TITLE
Pointer-sized integer types

### ISSUE THREAD

**Issue by winterhearted** [brendanzab/gl-rs#214]
Hi everyone

I am new in rust, so may be I propose some sheet.   

Now, in **gl-rs** the generator matches the pointer-sized integer types (like _GLintptr_) with types _i32_ or _i64_, depending on the platform. This implies platform-dependent fragments in the application code.
You could avoid this by using the _int_ type instead. According to the specification it is sized as a pointer but you don’t need to change it for each platform.

What is your opinion on this?

**Comment by bjz** [comment]
Is this still an issue?

**Comment by cmr** [comment]
I think so, yes. We should use isuze/usize for those types, now that Rust has settled its conventions about those.

**Comment by bjz** [comment]
PR welcome! At work now.

**Comment by bjz** [comment]
I've looked at [`gl_generator::generators::ty`](https://github.com/bjz/gl-rs/blob/master/gl_generator/generators/ty.rs), and I can't see any types that need changing... Has this been fixed, or could somebody point out the ones I need to fix?

**Comment by glennw** [comment]
It looks like they are defined as isize here https://github.com/bjz/gl-rs/blob/master/gl_generator/generators/ty.rs#L318 - is there somewhere else they need to be updated?

**Comment by brendanzab** [comment]
Seems like they are defined as `isize`, so I'm going to close this for now.
