### ISSUE TITLE
Set up auto-upload of docs via Travis

### ISSUE THREAD

**Issue by jarrett** [brendanzab/gl-rs#290]
I'm new to Rust, so I could be mistaken about this. Is there currently a problem with uploading the `gl-rs` docs to `rust-ci.org`? [This StackOverflow question](https://stackoverflow.com/questions/28196869/api-docs-for-gl-rs-rust-opengl-bindings/28200263?iemail=1&noredirect=1#28200263) is relevant.

**Comment by jarrett** [comment]
Look like `cargo doc` doesn't work at the moment:

    $ cargo doc
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Downloading log v0.2.1
    Downloading xml-rs v0.1.16
    An unknown error occurred

**Comment by bjz** [comment]
I'll need to set up auto-upload of the docs on travis
