### ISSUE TITLE
Vulkan support

### ISSUE THREAD

**Issue by brendanzab** [brendanzab/gl-rs#399]
Now that [Vulkan has been released](https://www.khronos.org/vulkan/), there is a question about whether it would make sense for gl-rs to support it (perhaps with a rename), or whether we should create a new project for this. Here is the new XML registry: https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/src/spec/vk.xml

**Comment by cmr** [comment]
I've created a [placeholder crate `vk`](https://crates.io/crates/vk). I think it makes sense to add Vulkan support to `gl_generator`, rename it to `khronos_api_generator`.

**Comment by cmr** [comment]
(I've added bjz and tomaka as owners to vk)

**Comment by tomaka** [comment]
One of the challenges of Vulkan is that you need four different structs that contain function pointers:

- functions to load with dlopen
- functions to load with `GetInstanceProcAddr(null, name)` (one of the functions to load is `CreateInstance`)
- functions to load with `GetInstanceProcAddr` but with an instance as parameter
- `GetDeviceProcAddr` with a device as parameter.

I don't think the XML files indicates that

**Comment by HeroesGrave** [comment]
@tomaka: I had a brief skim through the LunarG/Khronos loader and it appears that they just special-case the necessary functions.

> The Vulkan Loader exports all Vulkan core entrypoints and any other currently specifed exported extensions, which include the WSI extensions both instance and device.

> The Loader implements most entrypoints it exports via generic trampoline code and special terminator code for instance level entry points. Special handling is required for any Vulkan entrypoint with a VkInstance or VkPhysicalDevice dispatchable object as it's first parameter. Special loader handling is also required for `vkEnumerateInstanceLayerProperties()`, `vkEnumerateInstanceExtensionProperties()`, `vkCreateInstance()`, `vkDestroyDevice()`, `vkGetInstanceProcAddr()`, and `vkGetDeviceProcAddr()`.

The algorithm to determine which struct to use should be fairly simple:

- `GetInstanceProcAddr` appears to be given.
- `vkEnumerateInstanceExtensionProperties`, `vkEnumerateInstanceLayerProperties` and `vkCreateInstance` are loaded by calling `GetInstanceProcAddr(null, name)`
- Everything else is `GetInstanceProcAddr(instance, name)`.
- Any function in the previous group that has the first argument as a `VkDevice`, `VkQueue` or `VkCommandBuffer` may also be loaded using `GetDeviceProcAddr`.

Although hardcoded special cases is a nasty way of doing things, I don't expect any more edge cases to be added without the XML file being revised to include these details.

**Comment by Osspial** [comment]
Well, I've written a Vulkan symbol loader and generator, and it seems to work for the most part although I've only done limited testing. You can download it [here](https://github.com/Osspial/vk-rs). It currently lacks a struct-based function generator (which I'm working on) but that should be operational within the next few days. However, before I get around to documenting and publishing it on crates.io I'd like to ask: do you guys have any suggestions to improve the API or the default settings?

**Comment by brendanzab** [comment]
I think that we can close this - most people are using different libraries for working with Vulkan at this stage!
