### ISSUE TITLE
Output not deterministic

### ISSUE THREAD

**Issue by luser** [brendanzab/gl-rs#414]
I was investigating why sccache was not caching some parts of webrender (which @jrmuizel noticed) and I tracked it down to `gleam` using `gl_generator` to generate some source files, and those source files not being generated in a deterministic manner. [Here's a diff](https://gist.github.com/luser/354d77d2e202b93456c50e67cfdac36a) between two runs.

[gleam's build script](https://github.com/servo/gleam/blob/master/build.rs) doesn't seem to be doing anything unusual.

If I had to guess, I would guess it's due to [`Registry` using `HashSet` / `HashMap`](https://github.com/brendanzab/gl-rs/blob/d8c58776e9908d645ff651cfa27bfa2e20c8c954/gl_generator/registry/mod.rs#L94). Iterating over those items will not use a deterministic ordering. It should be simple enough to change those to `BTreeSet` / `BTreeMap` to fix that.

**Comment by luser** [comment]
I have a patch that compiles and passes tests: https://github.com/luser/gl-rs/commit/166771f9d79b51219507289ae76529bd093c975f .

I need to test it with a crate that does some generation to ensure that it fixes the issue.

**Comment by brendanzab** [comment]
Oooh, thanks for tracking this down!

**Comment by luser** [comment]
You're welcome! I originally thought bindgen was the problem and one of the bindgen authors mentioned that they use `BTreeMap` / `BTreeSet` everywhere for this exact reason, so I took a look at the `gl_generator` code and tried the obvious thing.
