### ISSUE TITLE
Support for SPIR-V extension

### ISSUE THREAD

**Issue by MatusT** [brendanzab/gl-rs#425]
Hello,

I wanted to use spirv extension in my OpenGL project, but when I tried adding GL_ARB_gl_spirv as an extension in my custom build.rs It did not generate corresponding functions and enums.

Here is my code:
`
    Registry::new(
        Api::Gl,
        (4, 5),
        Profile::Core,
        Fallbacks::All,
        [
            "GL_ARB_bindless_texture",
            "GL_ARB_seamless_cubemap_per_texture",
            "GL_EXT_texture_filter_anisotropic",
            "GL_ARB_gl_spirv"
        ],
    ).write_bindings(GlobalGenerator, &mut file)
        .unwrap();
`

Other extensions work without any problem. Is this problem related to gl_generator, khronos api, or did I do something wrong?

**Comment by tomaka** [comment]
The khronos_api crate probably needs an update.

**Comment by MatusT** [comment]
Successfully compiled and ran SPIR-V program using OpenGL after merge request. Huge thanks for helping with pull request and merging it! :)
