### ISSUE TITLE
Add WebGL support

### ISSUE THREAD

**Issue by nstoddard** [brendanzab/gl-rs#433]
I'm developing an app with emscripten + WebGL, and using gl-rs to generate the GL bindings. While WebGL and GLES are similar enough that GLES works, using GLES results in hundreds of (non-fatal) errors like "bad name in getProcAddress: glActiveShaderProgram,glActiveShaderProgram", and if you accidentally call a function that isn't supported by WebGL, it seems to jump to an arbitrary address. Adding WebGL support would prevent this kind of thing, and might also allow WebGL extensions.

**Comment by brendanzab** [comment]
Thanks for posting! I thought webgl was pretty much OpenGL ES 2.0? Couldn't you generate bindings for that profile? I might have to do some more research… 🤔

**Comment by brendanzab** [comment]
I do find it kind of concerning though that it "seems to jump to an arbitrary address". What are you using to call `getProcAddress`?

**Comment by nstoddard** [comment]
Here's what I'm using to generate the GL bindings:
```
Registry::new(
      Api::Gles2,
      (3, 0),
      Profile::Core,
      Fallbacks::All,
      [],
    ).write_bindings(gl_generator::StructGenerator, &mut file)
      .unwrap();
```

This results in about 180 "bad name in getProcAddress" errors like the one I mentioned above. I found this problem when trying to use glTexImage3D, which apparently isn't supported in webgl. I was seeing a divide by zero in jpeg-decoder, which didn't make sense because my app isn't even using that crate (since jpeg-decoder doesn't yet support emscripten). I added logging and found that the divide by zero happens during the call to glTexImage3D, which means that either it's somehow jumping to an address inside jpeg-decoder or misreporting where the error is happening.

I'm using glfw-rs. Emscripten apparently has its own implementation of glfw, which may be relevant.

**Comment by brendanzab** [comment]
It's odd that its printing 'bad name in getProcAddress' - I would have thought it would return a null pointer. Which is what we rely on in order to ensure the safety of these bindings. 🤔

**Comment by brendanzab** [comment]
Could you try [glutin](https://github.com/tomaka/glutin/#emscripten-with-asmjs) instead and see if you have the same issue?

**Comment by nstoddard** [comment]
Unfortunately it would be tricky to refactor to use glutin instead. I might try it when I have time, though it looks like emscripten recommends using its static GL bindings instead, so I might end up doing that instead if it's not too hard.

It looks like on Android, eglGetProcAddress() returns a valid address for any string: https://twitter.com/id_aa_carmack/status/387383037794603008?lang=en. So in general, it may not be a good idea to rely on checking for null. Not sure what the alternatives are though.

**Comment by nstoddard** [comment]
So it looks like this is probably a bug in emscripten: these APIs are in fact supported by WebGL 2, but for some reason they're not being loaded properly. I switched to StaticStructGenerator and it's working great.

I don't think there's anything that needs to be done in gl-rs to fix this, other than maybe documenting that StaticStructGenerator or StaticGenerator are needed when using WebGL.

**Comment by brendanzab** [comment]
@Diggsey seems to be wotking on this, as mentioned in #446

**Comment by Diggsey** [comment]
I'm working on direct WebGL bindings: it won't help with using WebGL via emscripten's GL => WebGL compatibility layer.

**Comment by brendanzab** [comment]
This should be done!

**Comment by DuckerMan** [comment]
So, how to use this with OpenGl?
