### ISSUE TITLE
brendanzab/glfw-rs doesn't exist

### ISSUE THREAD

**Issue by wizardfrag** [brendanzab/gl-rs#437]
In the [README.md for gl](https://github.com/brendanzab/gl-rs/tree/master/gl) it references glfw-rs, however the link doesn't exist. Should this link be pointing at [PistonDevelopers/glfw-rs](https://github.com/PistonDevelopers/glfw-rs)?

**Comment by brendanzab** [comment]
Yes, that's right! It used to be under my name.
