### ISSUE TITLE
What are the different generators?

### ISSUE THREAD

**Issue by SimonSapin** [brendanzab/gl-rs#453]
I couldn’t find what the different "generators" are, for example `StructGenerator` vs `GlobalGenerator`. Is there documentation on this?

(I’m trying to use ANGLE (to make WebRender and DirectComposition talk to each other) and it seems that its API is EGL, so the `gl_generator` crate can hopefully generate bindings for it.)

**Comment by tomaka** [comment]
It's in the README of gl_generator, so indeed a bit hidden: https://github.com/brendanzab/gl-rs/tree/master/gl_generator#generator-types

**Comment by SimonSapin** [comment]
Oh sorry, I was only looking at docs.rs… Filed https://github.com/brendanzab/gl-rs/pull/454, thanks.
