### ISSUE TITLE
Stdweb generator should use @(no_return)

### ISSUE THREAD

**Issue by jsheard** [brendanzab/gl-rs#457]
WebGL methods that aren't expected to return anything should use the `@(no_return) ` hint, to avoid the overhead of passing their return values back to Rust unnecessarily.

e.g.

```rust
pub fn clear(&self, mask: GLbitfield) {
    js!( @{self}.clear(@{mask}); );
}
```

should be

```rust
pub fn clear(&self, mask: GLbitfield) {
    js!(
        @(no_return)
        @{self}.clear(@{mask});
    );
}
```

**Comment by brendanzab** [comment]
Thanks for the report! cc. @Diggsey
