### ISSUE TITLE
Sound passing of null fn pointers

### ISSUE THREAD

**Issue by est31** [brendanzab/gl-rs#499]
There are some OpenGL APIs that allow passing of null function pointers: https://github.com/brendanzab/gl-rs/blob/667fbb36c3c629e83d4f7cb15a0e5aad52976051/gl_generator/generators/templates/types/gl.rs#L49 Rust function pointers however, even extern "system" ones, must not be null. Therefore, passing null to them is unsound and recent nightlies are warning about it (see https://github.com/glium/glium/issues/1775).

To fix this, I suggest wrapping an `Option<>` around the fn pointers in those type definitions.

**Comment by brendanzab** [comment]
Looks good! I see there is another two function pointers in egl - `EGLSetBlobFuncANDROID` and
`EGLGetBlobFuncANDROID`. Are those nullable too or are we good on that front?

**Comment by est31** [comment]
> Are those nullable too or are we good on that front?

Good point, I've had a look:

https://www.khronos.org/registry/EGL/extensions/ANDROID/EGL_ANDROID_blob_cache.txt

> If `<set>` or `<get>` is NULL then an EGL_BAD_PARAMETER error is generated. 

So requiring the fns to be non-null is okay.

**Comment by brendanzab** [comment]
Cool thanks a bunch!

**Comment by est31** [comment]
@brendanzab Thanks for merging! Could we get a new release? I guess it needs to be 0.14.0 because the API broke.

**Comment by brendanzab** [comment]
Sorry for the delay! This should be on crates.io now!
