### ISSUE TITLE
IntelliSense with Visual Studio Code doesn't work

### ISSUE THREAD

**Issue by Arvkus** [brendanzab/gl-rs#512]
Usually VSC offers to autocomplete for crate components, but it doesn't seem to work with this one whenever I type `gl::`.

I simply use `gl = "0.14.0"` in my cargo file and `extern crate gl;` in main.rs

**Comment by Lokathor** [comment]
The content of the crate is actually the result of a build script. Whatever VSC plugin you have probably doesn't work with build scripts.

**Comment by Arvkus** [comment]
Based on this [https://github.com/intellij-rust/intellij-rust/issues/1908](https://github.com/intellij-rust/intellij-rust/issues/1908) It seems that IntelliJ has autocomplete feature, but can't find anything to make it work with VSC. 
Tried `rust-analyzer` and `Rust (rls)` extensions. 
Probably I'll try to seek for help elsewhere.
