### ISSUE TITLE
GLenum is unsigned, but some GL functions needing enum values use a (signed) GLint

### ISSUE THREAD

**Issue by hikari-no-yume** [brendanzab/gl-rs#515]
`GLenum` is an unsigned integer type, `c_uint`, but some GL functions that need GL enum values take a `GLint`, and rustc complains about this. An example is `glTexParameteri`:

```
error[E0308]: mismatched types
  --> src/texture.rs:58:63
   |
58 |         gl::TexParameteri(gl::TEXTURE_2D, gl::TEXTURE_WRAP_S, gl::CLAMP_TO_EDGE);
   |                                                               ^^^^^^^^^^^^^^^^^ expected i32, found u32
help: you can convert an `u32` to `i32` and panic if the converted value wouldn't fit
   |
58 |         gl::TexParameteri(gl::TEXTURE_2D, gl::TEXTURE_WRAP_S, gl::CLAMP_TO_EDGE.try_into().unwrap());
   |                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Having to write `as GLint` isn't the worst thing in the world, but it is a little annoying. I wonder if there could be a nice solution to make such cases work without casting?

Obviously this is a very low-priority issue, especially since such cases are probably handled by higher-level libraries, and I don't expect anyone to fix it for me.

**Comment by Lokathor** [comment]
This is unfortunately a "bug" in how the GL.xml file specifies the functions and the fact that C will automatically convert values between types.

There is not much that can be done about this at the Rust layer

**Comment by daemonjax** [comment]
I noticed this inconsistency particularly with the internalformat parameter for both these functions:
TexTmage2D (GLint)
TexStorage3D (GLenum)

According to the kronos wiki, they should both be GLint.

**Comment by hikari-no-yume** [comment]
Yeah that's fair.
