### ISSUE TITLE
Bazel build fails

### ISSUE THREAD

**Issue by tudny** [brendanzab/gl-rs#543]
Hi!
We are migrating our small Rust project from Cargo to Bazel. 
We use [`Egui`](https://github.com/emilk/egui) and [`eframe`](https://docs.rs/eframe/latest/eframe/) for GUI and [`khronos_api`](https://docs.rs/khronos_api/3.1.0/khronos_api/) is its dependency. 
Unfortunately, we are experiencing some trouble with building the library.

The issue explained in the repo:
https://github.com/mimuw-jnp2-rust/project-matrix-busters/pull/45#issuecomment-1490919148
The repo itself (Bazel PR):
https://github.com/mimuw-jnp2-rust/project-matrix-busters/pull/45

**Comment by tudny** [comment]
The same problem was described here:
https://github.com/brendanzab/gl-rs/pull/536

It would be nice to handle it. Thanks!

**Comment by MarijnS95** [comment]
Fixed in https://github.com/rust-windowing/gl-rs/commit/cd187160d851657212689da7beb88c0d67a54696 🎉
